In [1]:
import pandas as pd
import math

In [2]:
dane = pd.read_csv("/home/niedakh/illimites/wbo/wbo-2015-analysis/data/processed/votes_with_city_wojewodztwo.csv", sep=';', encoding = "utf8")
dane

,Lp,Data,Wiek,Plec,Osiedle,Kod_Pocztowy,Zrodlo,Prog_1,Prog_2,Prog_3,Miasto,Wojewodztwo
0,1,"8:03:16, 28-09-2015",26,M,NaN,53-238,I,23,139,478,Wrocław,dolnośląskie
1,2,"8:04:10, 28-09-2015",26,K,Psie Pole-Zawidawie,51-314,I,376,709,115,Wrocław,dolnośląskie
2,3,"8:04:21, 28-09-2015",65,K,Krzyki-Partynice,53-010,I,459,0,0,Wrocław,dolnośląskie
3,4,"8:04:39, 28-09-2015",31,M,NaN,52-234,I,75,292,144,Wrocław,dolnośląskie
4,5,"8:04:59, 28-09-2015",20,M,Biskupin-Sępolno-Dąbie-Bartoszowice,51-670,I,469,364,170,Wrocław,dolnośląskie
5,6,"8:05:30, 28-09-2015",29,M,NaN,62-530,I,0,0,45,Kazimierz Biskupi,wielkopolskie
6,7,"8:06:18, 28-09-2015",32,K,Tarnogaj,50-515,I,428,0,0,Wrocław,dolnośląskie
7,8,"8:07:27, 28-09-2015",21,M,NaN,50-202,I,172,59,1,Wrocław,dolnośląskie
8,9,"8:07:29, 28-09-2015",35,M,Wojszyce,52-245,I,259,0,144,Wrocław,dolnośląskie
9,10,"8:08:04, 28-09-2015",35,M,Klecina,52-336,I,578,601,171,Wrocław,dolnośląskie
10,11,"8:08:06, 28-09-2015",36,M,Zacisze-Zalesie-Szczytniki,50-453,I,303,245,566,Wrocław,dolnośląskie
11,12,"8:08:11, 28-09-2015",31,M,Kuźniki,54-312,I,147,588,0,Wrocław,dolnośląskie
12,13,"8:08:26, 28-09-2015",77,M,Grabiszyn-Grabiszynek,53-229,I,0,0,136,Wrocław,dolnośląskie
13,14,"8:09:02, 28-09-2015",42,M,Zacisze-Zalesie-Szczytniki,50-305,I,303,214,566,Wrocław,dolnośląskie
14,15,"8:09:32, 28-09-2015",27,K,NaN,51-215,I,786,183,182,Wrocław,dolnośląskie
15,16,"8:09:32, 28-09-2015",45,K,NaN,54-104,I,360,0,354,Wrocław,dolnośląskie
16,17,"8:09:38, 28-09-2015",38,M,Przedmieście Oławskie,50-451,I,161,364,72,Wrocław,dolnośląskie
17,18,"8:09:56, 28-09-2015",25,M,Psie Pole-Zawidawie,51-314,I,15,219,115,Wrocław,dolnośląskie
18,19,"8:09:57, 28-09-2015",29,K,NaN,54-152,I,377,508,158,Wrocław,dolnośląskie
19,20,"8:10:34, 28-09-2015",40,M,NaN,52-234,I,0,0,144,Wrocław,dolnośląskie
20,21,"8:10:39, 28-09-2015",38,K,Żerniki,54-510,I,398,239,158,Wrocław,dolnośląskie
21,22,"8:11:04, 28-09-2015",49,K,Karłowice-Różanka,51-163,I,0,2,0,Wrocław,dolnośląskie
22,23,"8:11:16, 28-09-2015",49,K,Księże,52-013,I,255,256,405,Wrocław,dolnośląskie
23,24,"8:11:25, 28-09-2015",37,M,Krzyki-Partynice,53-326,I,0,803,0,Wrocław,dolnośląskie
24,25,"8:11:26, 28-09-2015",35,K,NaN,53-208,I,749,618,39,Wrocław,dolnośląskie
25,26,"8:11:31, 28-09-2015",39,K,NaN,51-354,I,718,707,39,Wrocław,dolnośląskie
26,27,"8:11:33, 28-09-2015",51,M,NaN,50-147,I,0,0,45,Wrocław,dolnośląskie
27,28,"8:12:10, 28-09-2015",57,K,NaN,50-202,I,377,508,158,Wrocław,dolnośląskie
28,29,"8:12:26, 28-09-2015",32,K,Krzyki-Partynice,53-025,I,752,491,171,Wrocław,dolnośląskie
29,30,"8:12:29, 28-09-2015",33,K,NaN,53-030,I,752,254,3,Wrocław,dolnośląskie
...,...,...,...,...,...,...,...,...,...,...,...,...
160146,160147,"7:26:43, 15-10-2015",41,K,NaN,NaN,P,719,735,427,NaN,NaN
160147,160148,"7:27:08, 15-10-2015",68,K,NaN,NaN,P,719,735,427,NaN,NaN
160148,160149,"7:27:22, 15-10-2015",37,M,NaN,NaN,P,0,0,478,NaN,NaN
160149,160150,"7:27:39, 15-10-2015",43,K,NaN,NaN,P,0,0,478,NaN,NaN
160150,160151,"7:29:11, 15-10-2015",64,M,NaN,NaN,P,62,80,478,NaN,NaN
160151,160152,"7:29:29, 15-10-2015",45,K,NaN,NaN,P,0,0,478,NaN,NaN
160152,160153,"7:29:42, 15-10-2015",59,M,NaN,NaN,P,0,0,478,NaN,NaN
160153,160154,"7:30:00, 15-10-2015",34,K,NaN,NaN,P,0,0,478,NaN,NaN
160154,160155,"7:30:16, 15-10-2015",22,M,NaN,NaN,P,0,0,478,NaN,NaN
160155,160156,"7:30:33, 15-10-2015",24,M,NaN,NaN,P,0,0,478,NaN,NaN
160156,160157,"7:31:08, 15-10-2015",28,M,NaN,NaN,P,0,0,478,NaN,NaN
160157,160158,"7:31:24, 15-10-2015",39,K,NaN,NaN,P,0,0,478,NaN,NaN
160158,160159,"7:31:36, 15-10-2015",19,M,NaN,NaN,P,0,0,478,NaN,NaN
160159,160160,"7:32:00, 15-10-2015",19,M,NaN,NaN,P,62,80,478,NaN,NaN
160160,160161,"7:32:16, 15-10-2015",18,M,NaN,NaN,P,0,0,478,NaN,NaN
160161,160162,"7:32:31, 15-10-2015",19,M,NaN,NaN,P,0,0,478,NaN,NaN
160162,160163,"7:33:21, 15-10-2015",52,K,NaN,NaN,P,0,0,478,NaN,NaN
160163,160164,"7:33:45, 15-10-2015",22,M,NaN,NaN,P,62,787,478,NaN,NaN
160164,160165,"7:34:12, 15-10-2015",21,K,NaN,NaN,P,62,787,478,NaN,NaN
160165,160166,"7:34:36, 15-10-2015",35,K,NaN,NaN,P,62,787,478,NaN,NaN
160166,160167,"7:34:52, 15-10-2015",59,K,NaN,NaN,P,0,0,478,NaN,NaN
160167,160168,"7:35:09, 15-10-2015",64,M,NaN,NaN,P,0,0,478,NaN,NaN
160168,160169,"7:35:25, 15-10-2015",65,K,NaN,NaN,P,0,0,478,NaN,NaN
160169,160170,"7:35:49, 15-10-2015",65,K,NaN,NaN,P,62,735,478,NaN,NaN
160170,160171,"7:36:10, 15-10-2015",65,K,NaN,NaN,P,62,735,478,NaN,NaN
160171,160172,"7:36:37, 15-10-2015",60,K,NaN,NaN,P,62,735,478,NaN,NaN
160172,160173,"7:38:03, 15-10-2015",27,M,NaN,NaN,P,0,0,478,NaN,NaN
160173,160174,"9:55:00, 15-10-2015",24,M,NaN,NaN,P,744,78,140,NaN,NaN
160174,160175,"10:33:05, 15-10-2015",43,K,NaN,NaN,P,259,295,144,NaN,NaN
160175,160176,"10:34:08, 15-10-2015",48,M,NaN,NaN,P,259,295,144,NaN,NaN

In [6]:
wroclaw = dane[dane['Miasto']==u'Wrocław']

In [3]:
wroclaw_votes = dane[(dane['Miasto']==u'Wrocław') & ((dane['Prog_1'] > 0)|(dane['Prog_2'] > 0)|(dane['Prog_3'] > 0))]

In [4]:
wroclaw_records = wroclaw_votes.to_records()

In [16]:
122220*0.000555992126465

67.9533576965523

In [8]:
project_votes = {}
for vote in wroclaw_records:
    for i in [-3,-4,-5]:
        p = vote[i]
        if p not in project_votes:
            project_votes[p] = []
        project_votes[p].append(vote[1])
del project_votes[0]

In [9]:
votes_to_codes = { vote[1] : vote[-7].replace('-','') for vote in wroclaw_records }

In [10]:
codes_from_votes = { vote[-7].replace('-','') : {} for vote in wroclaw_records }

In [14]:
s = time.time()
for vote in wroclaw_records:
    code = vote[-7].replace('-','')
    p_v = [vote[i] for i in [-3,-4,-5] if vote[i] > 0]
    for p in p_v:
        for vid in project_votes[p]:
            cooccured_code = votes_to_codes[vid]
            if cooccured_code not in codes_from_votes[code]:
                codes_from_votes[code][cooccured_code] = []
            
            codes_from_votes[code][cooccured_code].append(vid)
            break
        break
    break
print(time.time()-s)

0.000555992126465

In [17]:
rpkec

[478, 139, 23]